project:
  type: website
  resources:
    - objects.json

website:
  navbar:
    left:
      - href: https://machow.github.io/quartodoc/
        text: quartodoc home
      - file: reference/index.qmd
        text: "Reference"
    right:
      - icon: github
        href: https://github.com/machow/quartodoc/tree/main/examples/pkgdown



quartodoc:
  style: pkgdown
  dir: reference
  package: quartodoc
  sections:
    - title: Some functions
      desc: These functions inspect and parse docstrings.
      contents:
        - get_object
        - preview
