[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2", "watchdog>=3.0.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
]
testpaths = [
    "quartodoc/tests"
]

[tool.setuptools_scm]
