[build-system]
requires = ["setuptools>=45,<=58", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
]
testpaths = [
    "tests.py"
]

[tool.setuptools_scm]

[project.scripts]
quartodoc = "quartodoc.cli:main"
