project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown

filters:
  - "interlinks"

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/

quartodoc:
  style: pkgdown
  dir: api
  package: quartodoc
  sections:
    - title: API Builders
      desc: |
        Builders are responsible for building documentation. They tie all the pieces
        of quartodoc together, and can be defined in your _quarto.yml config.
      contents:
        - Builder
        - BuilderPkgdown
        - BuilderSinglePage

    - title: Docstring Renderers
      desc: |
        Renderers convert parsed docstrings into a target format, like markdown.
      contents:
        - MdRenderer

    - title: Inspection
      desc: |
        These functions Fetch and analyze python objects, including parsing docstrings.
      contents:
        - get_object
        - preview

    - title: Inventory links
      desc: |
        Inventory files map a functions name to its corresponding url in your docs.
        These functions allow you to create and transform inventory files.
      contents:
        - create_inventory
        - convert_inventory


website:
  title: "quartodoc"
  page-navigation: true
  navbar:
    left:
      - file: get-started/overview.qmd
        text: Get Started
      - file: examples/
        text: Examples
      - href: api/
        text: Reference
    right:
      - icon: github
        href: https://github.com/machow/quartodoc/
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - get-started/overview.qmd
        - section: "Basics"
          contents:
            - get-started/basic-docs.qmd
            - get-started/crossrefs.qmd
            - get-started/sidebar.qmd
        - section: "Advanced"
          contents:
            - get-started/docstrings.qmd
            - get-started/renderers.qmd
            - get-started/interlinks.qmd
        - section: "Extra Topics"
          contents:
            - get-started/architecture.qmd
    - id: dummy


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
