project:
  type: website
  output-dir: _build
  resources:
    - objects.json

filters:
  - "interlinks"

interlinks:
  sources:
    quartodoc:
      # TODO: how to have it be "site root"?
      url: "/"
      inv: null
      fallback: objects.json

website:
  title: "quartodoc"
  navbar:
    left:
      - file: get-started/overview.qmd
        text: Get Started
      - href: api/
        text: Reference
    right:
      - icon: github
        href: https://github.com/machow/quartodoc/
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - section: "Basics"
          contents:
            - get-started/overview.qmd
            - get-started/basic-docs.qmd
            - get-started/crossrefs.qmd
        - section: "Advanced"
          contents:
            - get-started/docstrings.qmd
            - get-started/interlinks.qmd
    - id: dummy


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
